language: node_js
node_js:
  - 6
  - 5
  - 4
before_install:
  - npm config set depth 0
  - npm install --global npm@3
notifications:
  email: false
sudo: false
script:
  - npm run test
  - npm run lint
