language: node_js
node_js:
  - node
  - 8
  - 6
before_install:
  - npm config set depth 0
notifications:
  email: false
sudo: false
script:
  - npm run test
  - npm run lint
  - npm run build
after_success:
  - export NODE_ENV=production
  - npm run build
  - "npm run create-readme && git add README.md && git commit -m 'docs: generate docs' --no-verify"
  - semantic-release
  - git push
